### ISSUE TITLE
Can't find my most recent repo to add from my GitHub account

### ISSUE THREAD

**Issue by g0t4** [microsoft/devhome#1050]
### Dev Home version

0.137.141.0

### Windows build number

10.0.23471.1000

### Other software

OS Build Version: 10.0.23471.1000.amd64fre.ni_prerelease.230526-1341
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

On the add repo page, when I type in the search box to find a repo to add, including the most recent repo I created and modified... it does not show in the filtered repos. FYI, the repo is not brand new, it was created a week ago.  

Furthermore, when I scroll through the list it does not show (unless I missed it, I have 204 repos total). I scanned the list twice. 

Separately, repos that initially appear in the list--that would match the text typed into the search box--mostly disappear once I type in text. It appears the search matches on `starts-with` and not `contains` as I would expect. 

### Expected result

Filter and pick a given repo to add/clone. 

### Actual result

2 overlapping issues:
- Search is `starts with` and not `contains` 
- Some repos don't appear in the list

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
Physical Memory: 31.84GB (21.66GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by dhoehna** [comment]
Hello!  

A note about the Repo limit.  You did hit it.  The extension returns
1. Max 50 most recently updated user private repos
2. Max 50 most recently updated org repos (mix of private and public)
3. Max 50 most recently updated user public repos.

I am sorry you ran into this limit.

This list, max number, and ordering is not final.  I'm talking with PMs to figure out a better way to grab and display repositories.

On the steps to reproduce the bug.
Is it possible between making the repo and trying to clone it with DevHome, 50+ other repos have been updated?

Otherwise can you provide me with the exact repro steps?

**Comment by g0t4** [comment]
That makes sense.

Per `gh repo list` it is still one of the most recent updated repos coming
in at #4 right now.

**Comment by g0t4** [comment]
FYI you should be able to see my list of public repos with `gh repo list g0t4`

**Comment by dhoehna** [comment]
I'm looking into this and noticed that DevHome is displaying the repos in reverse order.  I modified DevHome to show the repos in date descending order.  Now the repos are displayed from newest to oldest.

You stated that you could not find one of your updated repos in the repo list.  However, even if DevHome displayed the repos in the wrong order, you still should have seen your most recently updated repos and that tells me the extension is not grabbing the correct repos.

Question.  Is it only 1 repo that you can't find, or do multiple repos not show up?
