### ISSUE TITLE
Visual Studio 2022 Enterprise is not selectable

### ISSUE THREAD

**Issue by digitaldias** [microsoft/devhome#1116]
### Suggested new feature or improvement

I have a license for Visual Studio 2022 Enterprise, and I'm  currently on the latest preview. It's quite the let-down that this isn't selectable as an app. 

### Scenario

To explore Dev Home from a more professional angle.

**Comment by AmelBawa-msft** [comment]
@digitaldias, thank you for creating this request. Is "Visual Studio 2022 Enterprise" not selectable from the "Install applications" page in Dev Home after searching for it? Is the application already installed on the machine?

**Comment by digitaldias** [comment]
It is already installed on the machine

**Comment by AmelBawa-msft** [comment]
Correct, if an application is already installed we disable the select button. Here's an example of the current expected behavior:
<img src="https://github.com/microsoft/devhome/assets/104940545/5870d3a9-0ef8-4b18-af12-7ca7a42c41a8" Width="500" />
In the screenshot above, "Visual Studio Enterprise 2022" is installed (select button disabled) whereas "Visual Studio Enterprise 2019" is not installed (select button enabled).

Adding @mathewleeza to help triage the widget question.
