### ISSUE TITLE
What's New page does not have 8 px rounded corner when window is small

### ISSUE THREAD

**Issue by LiCaoZ** [microsoft/devhome#1246]
### Dev Home version

0.200.170.0

### Windows build number

10.0.23493.1000

### Other software

OS Build Version: 10.0.23493.1000.amd64fre.ni_prerelease.230624-1828
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Open Dev Home, Anywhere
![image](https://github.com/microsoft/devhome/assets/67832651/64573e70-df2a-4ead-b831-a4e6411524a3)
![image](https://github.com/microsoft/devhome/assets/67832651/f9f75281-10f5-4864-816b-9182bfe45825)

Here are some screenshots of WinUI 3 Gallery so we can compare:

![image](https://github.com/microsoft/devhome/assets/67832651/f423aa11-696c-4995-9a7d-04406f652378)
![image](https://github.com/microsoft/devhome/assets/67832651/706ecc3a-a595-4389-a3fe-45790e4c57e5)

### Expected result

According to Microsoft WinUI 3-related design specifications and the display of WinUI 3 Gallery, the page container and sidebar should use different levels of background color, and there should be 8px rounded corners at the top of the junction.

### Actual result

It's supposed to appear with rounded corners and different hierarchies, but it doesn't

### Included System Information

Physical Memory: 11.89GB (2.67GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.200.170.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.200.165.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
This coloring, where the page container and the sidebar have the same color, was specifically requested by the designers. Here's the PR where we implemented it: https://github.com/microsoft/devhome/pull/265

Also, the pages do have rounded corners. If you change the color of NavigationViewContentGridBorderBrush, you can see it:
![image](https://github.com/microsoft/devhome/assets/47155823/c2bb3386-94aa-4b50-b853-b706bcbe6b32)

I suspect you're seeing the right angle when the window is narrower than the page's min width. Since the background image is set to Stretch=UniformToFill ([link](https://github.com/microsoft/devhome/blob/b1a30b527d87d56a1c0f78bacce690d9a4f86eff/src/Views/WhatsNewPage.xaml#L37C163-L37C186)), the rounded corner of the image is being squished when the window is narrow. Setting a rounded corner on the containing grid should keep the corner round, even when the underlying image's corner is no longer round.
