### ISSUE TITLE
Core widgets showing variable names

### ISSUE THREAD

**Issue by darrix** [microsoft/devhome#1248]
### Dev Home version

0.200.170.0

### Windows build number

10.0.23493.1000

### Other software

OS Build Version: 10.0.23493.1000.amd64fre.ni_prerelease.230624-1828
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Attempt to create CPU, memory, or other non-GitHub widgets.  After opening (and pinning) you see text where the display should be

### Expected result

Graphic display of widget

### Actual result

Widget included text description of detail, e.g., ${usedMem} ${allMem}

### Included System Information

Physical Memory: 31.84GB (15.69GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.200.170.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.200.165.0_x64__8wekyb3d8bbwe

**Comment by biiigwang** [comment]
### Dev Home version

0.601.297.0

### Windows build number

10.0.22631.2428

### Other software

OS Build Version: 10.0.22631.2428.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

1. Update the system to Windows 11 23H2,
2. Open Dev Home,
3. Enter the dashboard to add widgets and fix them.

### Expected result

I hope to display the content in the widget normally.

### Actual result

There are no numerical values in the content of the widget, only placeholders.
![Photo](https://github.com/microsoft/devhome/assets/26035594/6afc1a7d-419b-42b4-8cf5-445f0b394e3a)


### Included System Information


Physical Memory: 15.34GB (8.86GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe

**Comment by galenelias** [comment]
I took a look at this today on my machine, and it appears at least for me this is due to the expected PerformanceCounterr/PerformanceCounterCategories not being present on my machine. The first error I hit is:

```
InvalidOperationException: Category 'GPU Engine' does not exist.

    System.Diagnostics.PerformanceCounterLib.GetCategorySample(string, string)
    System.Diagnostics.PerformanceCounterCategory.GetCounterInstances(string, string)
    CoreWidgetProvider.Helpers.GPUStats.GetGPUPerfCounters() in GPUStats.cs
    CoreWidgetProvider.Helpers.GPUStats.GPUStats() in GPUStats.cs
```

And to confirm, if run the following PowerShell script on my non-functional machine, I get:
```
> Get-Counter -ListSet 'GPU Engine*'
Get-Counter: Cannot find any performance counter sets on the localhost computer that match the following: GPU Engine*.
```
Whereas on my working machine it returns a bunch of information as expected.

If I comment out the GPUStats code, then I see that I then start failing trying to instantiate the `Processor Information` `PerformanceCounter` in `CPUStats`.  Similarly, running the `Get-Counter` command yields similar results for `'Processor Information*'`.  So, I'm not sure why my machine is missing all these performance counters, and where they are supposed to be coming from on a 'normal' system.

So, not sure if this is the same issue other people hitting this are having, but if the required PerformanceCounters aren't present then I'm not sure there is likely anything reasonable for the Widget's to do, other than fail in a more obvious or intentional way.

**Comment by dkbennett** [comment]
Actively working on a fix here. The planned fix is adding error messages into the core widgets and bubbling up actual error messages. So it will no longer show variable names if it fails, it will instead give you a better message. That fixes the issue of showing variable names.

However, the underlying issue of why it is showing variable names - perf counters missing - that is a trickier problem. It seems like that is an unspecified OS dependency, which would either have to be resolved at install time or by the user at run time after encountering the issue. Given that the dependency might be removed at any time later, the runtime identification of the error with documentation on how to restore the perf counters would be appropriate.
