### ISSUE TITLE
[CI]: GitHub Token isn't created for WinGet Package Submissions

### ISSUE THREAD

**Issue by mdanish-kh** [microsoft/devhome#1307]
### Steps to reproduce the bug

Take a look at the CI run: https://github.com/microsoft/devhome/actions/runs/5601484465/jobs/10245701244

winget-create fails with error `Option 't, token' has no value.`. This suggests that a token named `WINGET_PAT` defined in `.github/workflows/winget-submission.yml` wasn't added as a repository secret. 
https://github.com/microsoft/devhome/blob/752fb8a2a5a1bf4266e222c83313b4d967f760b1/.github/workflows/winget-submission.yml#L13-L17

Instructions on creating the classic token can be found over at the [winget-create repo](https://github.com/microsoft/winget-create#github-personal-access-token-classic-permissions). This should be added as a repository secret here in the DevHome repo. I'm not entirely sure but I think @cinnamon-msft is the best candidate for the creation of this token as she publishes the GitHub releases (could be wrong on this one tho).

### Expected result

`WINGET_PAT` repository secret to be referenced properly for the CI

### Actual result

CI failing as it could not find the token

**Comment by mdanish-kh** [comment]
Yes, I added the link to the winget-create documentation for this in the issue (https://github.com/microsoft/winget-create#github-personal-access-token-classic-permissions). In short, it needs to be a classic token with `public_repo` scope

**Comment by vineeththomasalex** [comment]
The above issue has been fixed as suggested. 

Adding this new problem with the run to this issue, rather than creating a new issue:
https://github.com/microsoft/devhome/actions/runs/5601484465/jobs/10247807816

"The number of new installer packages must match the number of existing installer packages." 
This was [expected to be fixed](https://github.com/microsoft/winget-create/issues/166#issuecomment-1563201903) with the latest winget-create.  The team is looking into it, and will close this issue after that has been fixed.

**Comment by vineeththomasalex** [comment]
The above problem was fixed with https://github.com/microsoft/winget-create/pull/411 in [Winget-create v1.2.8.0](https://github.com/microsoft/winget-create/releases/tag/v1.2.8.0)

https://github.com/microsoft/devhome/actions/runs/5601484465/jobs/10251950868
Latest run worked. Closing this issue.
