### ISSUE TITLE
Infinite downloads

### ISSUE THREAD

**Issue by Chucho0** [microsoft/devhome#1480]
### Dev Home version

0.401.226.0

### Windows build number

10.0.23536.1000

### Other software

OS Build Version: 10.0.23536.1000.amd64fre.ni_prerelease.230826-1546
.NET Version: .NET 6.0.20

### Steps to reproduce the bug

estaba descargando aplicaciones y lleva ya mucho tiempo descargandolas

### Expected result

una descarga normal 

### Actual result

sigo esperando la descarga 

### Included System Information

Physical Memory: 31.85GB (25.57GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.401.226.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.400.226.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
Bing Translate:

Infinite downloads

I was downloading apps and has been downloading them for a long time

a normal download

I'm still waiting for the download

**Comment by AmelBawa-msft** [comment]
@Chucho0, thank you for opening this issue and sorry for the delayed response. This issue was resolved in this PR:

- https://github.com/microsoft/devhome/pull/2089
  - Added recovery when RPC exceptions occur.

And further enhancements have also been applied in the PRs below:
- https://github.com/microsoft/devhome/pull/3134
  - Elevated process now uses the same WinGet logic as Dev Home's main process (enhanced implementation overall + recovery)
- https://github.com/microsoft/devhome/pull/3307
  - Mitigated an issue that occurs when Dev Home's elevated process attempts to install multiple packages at the same time. 

Would it possible to help validate that this issue no longer repros on latest Dev Home?
