### ISSUE TITLE
First Experiences - Multiple Bugs

### ISSUE THREAD

**Issue by MyriadSoft** [microsoft/devhome#1606]
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2361

### Other software

OS Build Version: 10.0.22621.2361.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

1. When I first launched, I was very confused as to why creating an account requires an extension. That seems incredibly unintuitive and should be built in by default, not an extension.

2. When I added the required extension for account management, the entire application froze for a short period (less than 1 minute) before terminating. Once I reopened it, the extension was installed, so it appears a reboot was necessary but it was not automated and I received no message so it appears as a crash.

3. When I started it back up and went to login, the "Sign in to GitHub.com" window popped up as expected, but clicking the button did nothing. After 30 or so clicks, with some delay in between, I closed the window. Once I opened the window again, the button worked fine on the first try.

4. The application name ("Dev Home (Preview)") isn't aligned properly, nor is the settings icon to its left. They're both slightly too low such that they leak into the main window contents. (Edit* This, like the previous bug, seems to have resolved itself.)

5. This is a minor gripe and tangentially related to my first point, but it's particularly strange that account management requires an extension while then seeing it's the only extension available for Dev Home in the MS Store. It almost appears as though the MS Store and extension capabilities are being advertised, but in the strangest way imaginable. Obviously I don't know if that's the case, just what my thoughts were upon experiencing it.

### Expected result

Just a bit of a less buggy product, though I know this is just a preview.

### Actual result

Explained earlier.

### Included System Information

Physical Memory: 63.15GB (52.35GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
Hi @MyriadSoft. I'm sorry you hit so many issues. To address some of them:
1. You don't need to add any accounts to Dev Home in order to use it. It might be on us to make that more clear. At the moment, the GitHub Extension is the only extension, so it may seem like the "default" account, but it's not really. In the future, when you have more options for what extensions you want to install, hopefully the extension model will make more sense.
2. I thought we had an issue open for this, but I'm not seeing it... let me dig around a little more and I'll open one if I can't find it.
3. This is a known intermittent bug with Adaptive Cards. It's being tracked by #1544
4. This kind of sounds like #562 to me, but I never noticed it resolved itself. Interesting.
5. Hopefully my answer to 1 made sense, but I'll add that another benefit of the extension model is that we're not forcing anyone to have or use an extension they don't want.

**Comment by krschau** [comment]
@MyriadSoft Can you open a new issue for your "Installing an extension while Dev Home was running crashed Dev Home" problem? If you open it via Dev Home instead of me, it will collect some helpful info from your machine.
