### ISSUE TITLE
Can't uninstall Dev Home

### ISSUE THREAD

**Issue by LandonBoi123** [microsoft/devhome#1615]
### Other software

I updates windows, and I got this crap... Everyone is mad so please let us uninstall this, but no it's just more bloatware...

### Steps to reproduce the bug

Update windows

### Expected result

it installs itself

### Actual result

it installs itself through the microsoft store and doesn't allow you to uninstall it.

**Comment by domoaligato** [comment]
I would also like to uninstall this. I do development on separate hardware from my other pc's and don't want this on them. Also why was this pushed to everyone if it is preview? I would understand more if it was GA.

**Comment by SimonCropp** [comment]
try 
```
winget uninstall "DevHome"
```

**Comment by SimonCropp** [comment]
and i am adding it to WinDebloat https://github.com/SimonCropp/WinDebloat/pull/58

**Comment by Hamberfim** [comment]
👍 on this one since mine (Unable to Uninstall #1816 | https://github.com/microsoft/devhome/issues/1816) was a duplicate.

**Comment by bugnumber9** [comment]
Such features should be opt-in and not opt-out, especially with no easy way to opt-out.

**Comment by domoaligato** [comment]
> Can we get an explanation as to **why** this was automatically pushed to users? Was this a mistake or a conscious decision, and if so, what was the reasoning?

100% this should not have been automatically pushed to anyone. 
This shouldn't even be considered a preview.

What is the ruleset to determine if someone gets this deployment or not? 
I am not currently enrolled in an insider preview for Windows, vscode, windows terminal, wsl, nothing.

**Comment by cinnamon-msft** [comment]
We appreciate your feedback on the delivery of Dev Home and we are working on a plan to address it. Dev Home is a system component to enhance the developer experience on Windows. Windows strives to deliver better experiences for all kinds of users: for instance, Windows provides Game Bar for gamers, and Dev Home falls into a similar category. We thank you for your patience.

Examples of system features we're looking to implement include: https://github.com/microsoft/devhome/issues/1983, https://github.com/microsoft/devhome/issues/679, https://github.com/microsoft/devhome/issues/677

**Comment by SimonCropp** [comment]
@cinnamon-msft seems there has been a reasonable amount of people who have pushed back on the approach to deploying devhome through a windows update. Is there any "lessons learnt" response from MS where we can see the changes in the decision making process so this wont happen again?

**Comment by Namefi** [comment]
open PowerShell as administrator and paste this in " Get-AppxPackage Windows.DevHome | Remove-AppxPackage"

**Comment by Hamberfim** [comment]
> open PowerShell as administrator and paste this in " Get-AppxPackage Windows.DevHome | Remove-AppxPackage"

Can anyone confirm this actually works as uninstall?

**Comment by Namefi** [comment]
To confirm do the command then in Microsoft store look for dev home

**Comment by bugnumber9** [comment]
> > open PowerShell as administrator and paste this in " Get-AppxPackage Windows.DevHome | Remove-AppxPackage"
> 
> Can anyone confirm this actually works as an uninstall method?

It does.

**Comment by Paper-Folding** [comment]
> open PowerShell as administrator and paste this in " Get-AppxPackage Windows.DevHome | Remove-AppxPackage"

Works, but in my windows 11 pc, `Get-AppxPackage -name *DevHome* | Remove-AppxPackage` works

**Comment by isendrak** [comment]
> Windows strives to deliver better experiences for all kinds of users: for instance, Windows provides Game Bar for gamers, and Dev Home falls into a similar category.

Well, fuck it! Make shit like that optional! Don't just dump your trash on people's devices without their consent! FUCK YOU!

BTW: I hope those guys who made the infamous "Cookie Consent Law" come around to fuck your fucking asses!!!

**Comment by pawel38911** [comment]
> Windows strives to deliver better experiences for all kinds of users: for instance, Windows provides Game Bar for gamers, and Dev Home falls into a similar category.

Yes, of course XD
Don't be ridiculous!
You're a damn monopolist, you don't care about the customer's opinion at all, because most of your customers have nowhere else to go anyway!
Statistics show that you are one of the most hated companies by your own customers.

**Comment by cinnamon-msft** [comment]
@isendrak @pawel38911 We encourage constructive criticism and passionate discussion, but please keep your tone respectful, as per the project’s [Code of Conduct](https://opensource.microsoft.com/codeofconduct/).

**Comment by isendrak** [comment]
@cinnamon-msft
> but please keep your tone respectful

Blah! If you want respectfullness, then earn it.
Forcing shitty bloatware onto users without their consent and then making it extra hard to remove it only earns you a fucking shitstorm (at best).

**Comment by Paper-Folding** [comment]
@cinnamon-msft Dear developer from Microsoft, could you please tell me how to uninstall "Windows Backup" and "Get Started"? I was struggling with these bloatware, too!

**Comment by TubaOrNotTuba** [comment]
Dear Microsoft and @cinnamon-msft 

When you delete comments you only PROVE you are hiding something.  ONLY companies with things to hide hide things.  You assume Github users aren't capable of differentiating from legitimate, productive comments and abusive ones.  While I agree that some of the comments may be less than light and cheery in tone, Microsoft created this situation by installing, potentially illegally in some locations as you do not obtain specific permission to install code on customer-owned computers, unwanted and unnecessary software.  99.9999% of your users do NOT need Dev Home.  That number might even be higher, I'm just being generous, but that you don't allow users to remove it suggests to everyone you have ulterior motives.

So in the end, when you delete comments you reinforce that you are hiding something.  As a 32-year Microsoft partner and a long-time shareholder, as well as a customer, I implore you to reconsider your actions and behaviour here yourself.  I have one larger customer who finally has had enough of Microsoft's behaviour and since they are almost entirely web-based now, they have only one remaining on-site line-of-business applicaiton and that goes web-based this summer, we have begun working with them to transition to Ubuntu, leaving 100% of Microsoft products behind.  By August, they will have zero Microsoft software in use.  You did this.  You created this situation and this customer will not be alone.  You are riding high on Azure cloud sales, but there is absolutely nothing that Azure does that can't be done in a competing system, often for less $.  Continue down this road and even the smallest of customers and consumers will eventually reach the same conclusion and then you will be the ones without jobs.

![image](https://github.com/microsoft/devhome/assets/27431511/de8986a4-dffc-4492-bfc9-84ebccbac169)

**Comment by SimonCropp** [comment]
@TubaOrNotTuba thanks for leading the way with your OSS contributions

![image](https://github.com/microsoft/devhome/assets/122666/803270e5-83f9-4b89-83e9-0059303f0c15)

**Comment by pawel38911** [comment]
> I have one larger customer who finally has had enough of Microsoft's behaviour and since they are almost entirely web-based now, they have only one remaining on-site line-of-business applicaiton and that goes web-based this summer, we have begun working with them to transition to Ubuntu, leaving 100% of Microsoft products behind. 

I went through a similar process on my home computer :)
Microsoft's arrogance and brutality long ago exceeded acceptable limits.

Windows has virtually everything I need, both for work and play. However, Microsoft's policy in recent years, particularly its brutal violation of its customers' privacy and freedom to manage their own home computer, has prompted me to abandon my favorite software and games, switching to Linux.


Let me emphasize again:

The Windows environment has everything I need and expect. 
Despite this, I gave up Windows and migrated to the Linux environment, which lacks many things I like and need, while many other things work noticeably worse than on Windows. 
I decided to give up the convenience and richness of the Windows environment because Linux gives me something that Microsoft brutally took away from me: my freedom and privacy. 
I understand that freedom has a price, and I that price I am willing to pay.


Don't want an AI assistant on your home computer? 
On Linux you don't have to. 
On Windows you do have to.

Don't want to receive an operating system update?
On Linux you don't have to. 
On Windows you do have to.

Don't want to try a professional tool for things you not only don't need but don't even understand what they're for?
On Linux you don't have to. 
On Windows you do have to.

Do you like retro style and miss the neat interface of Windows 98?
On Linux you can make your modern operating system look like Windows 98. 
On Windows 11 you can't.


The longer I stay on Linux, the more tools and toys I create for myself in the Linux environment, the less likely it is that I will ever go back to the Windows environment.

And, of course, during that time I will dissuade everyone from using Microsoft products, and actively help them abandon the Windows environment. Because a little drop drills a hard rock. Such black matketing for you.

**Comment by R-Adrian** [comment]
on Windows 10... got a unwelcome surprise seeing the devhome app appear after a windows update.
The uninstall button was still greyed out even after 24h passed and multiple system reboots.

I tried running the normal `get-appxpackage *devhome* -allusers | remove-appxpackage -allusers`  but that did not work at all because the app was tagged as staged by the SYSTEM account.... so i had to run powershell as the system account to nuke it:

- get Sysinternals Suite  / Sysinternals PSTools
- `PsExec64.exe -sdi powershell.exe`
- in the new window run:
a) `whoami` - to verify you are running as `nt authority\system`
b)  `Get-AppxProvisionedPackage -Online |  % {if ($_.DisplayName -eq "Microsoft.Windows.DevHome") {$_}}  |  Out-String -Stream`  - just to verify the correct thing to be removed next
c)  **`Get-AppxProvisionedPackage -Online |  % {if ($_.DisplayName -eq "Microsoft.Windows.DevHome") {$_}}  | Remove-AppxProvisionedPackage -Online`**

**Comment by babywannabeastar** [comment]
Hello,

After a recent update I have discovered that Dev Home is auto installing in our environment. Is there a way to prevent this app from automatically installing (or any un-consented microsoft product) via GPO?

Not a dupe looking for a gpo related method to prevent this from happening in the future.

winver 23H2 OS Build 22631.4037

Thank You

**Comment by dstack4273** [comment]
> We appreciate your feedback on the delivery of Dev Home and we are working on a plan to address it. Dev Home is a system component to enhance the developer experience on Windows. Windows strives to deliver better experiences for all kinds of users: for instance, Windows provides Game Bar for gamers, and Dev Home falls into a similar category. We thank you for your patience.
> 
> Examples of system features we're looking to implement include: [#1983](https://github.com/microsoft/devhome/issues/1983), [#679](https://github.com/microsoft/devhome/issues/679), [#677](https://github.com/microsoft/devhome/issues/677) 

This was commented almost a year ago - where is the change in the release plan? What semester? What is the ETA? Making a comment like this and nearly a year has passed is a pretty terrible show of concern or regard for users from Microsoft.

**Comment by TubaOrNotTuba** [comment]
> > We appreciate your feedback on the delivery of Dev Home and we are working on a plan to address it. Dev Home is a system component to enhance the developer experience on Windows. Windows strives to deliver better experiences for all kinds of users: for instance, Windows provides Game Bar for gamers, and Dev Home falls into a similar category. We thank you for your patience.
> > Examples of system features we're looking to implement include: [#1983](https://github.com/microsoft/devhome/issues/1983), [#679](https://github.com/microsoft/devhome/issues/679), [#677](https://github.com/microsoft/devhome/issues/677)
> 
> This was commented almost a year ago - where is the change in the release plan? What semester? What is the ETA? Making a comment like this and nearly a year has passed is a pretty terrible show of concern or regard for users from Microsoft.

That's because Microsoft couldn't care less. His excuse that they include game bar for gamers is the same as including Dev home for developers is the same recycled garbage  that 99.9% of us don't care about. I've never once used the game bar because I'm not a gamer and I've also never once used Dev home because I'm not a developer. You know, I build networks for a living, how about tools to hot map Wi-Fi access points in and around buildings? Even home users have those devices and commercial software to do that is expensive so maybe they should include those as well? This is just garbage from Microsoft that they force on people because they don't want to take the time to write code that no one ever sees and no one will ever install. Some developer and product manager managed to con the Windows product manager into including this to justify their jobs, when what should have happened was the Windows product manager should have turned the request into some SVP to have those programmers and product managers fired for trying to weasel their way into the operating system and make it even more bloated than it already is.

**Comment by hayos** [comment]
As it is somehow no more possible to create local Environments, I wanted to uninstall/re-install Dev Home via Microsoft Store, Add/Remove programs or Dev Home (Preview) itself. In Dev Home itself it should be via Extensions -> 'Dev Home (Preview)' -> ... -> Uninstall.
Neither works. My version 0.1801.640.0.

If you have a look at the comments in Microsoft Store, you will soon realize that many (non-developer) users do not agree with the fact that they cannot uninstall Dev Home. (If they really have it installed or just see the installer application stays being their secret). The overall rating is at 1.4 stars, which is fourth floor subterrane.

**Comment by mcgonrya** [comment]
This is part of a broader issue that Microsoft fails to accept and address in a way that actually means something. Over the last few years, Microsoft has repeatedly used Windows updates to install random software without user consent. OS updates should be used to fix problems, yet the new style of forcing updates (can't stop them, and even if you remove specific updates, the same changes appear in the next cumulative update) in Windows has been repeatedly abused by Microsoft to install garbage bloatware on PCs with no consent or even a forewarning. Feedback through Microsoft's own Feedback Hub in Windows does absolutely nothing, as I have sent feedback countless times stating how frustrating this is.

Consumers are tired of it, but Microsoft doesn't care in the slightest bit as they know the majority of people can't switch away from Windows. To make matters even worse, not only does Microsoft acknowledge concerns and fail to address them, Microsoft attempts to silence people who voice their concerns in public forums by deleting their comments. This is a disgrace.
