### ISSUE TITLE
Panel loading

### ISSUE THREAD

**Issue by NicolasZFr** [microsoft/devhome#1799]
### Dev Home version

0.601.297.0

### Windows build number

10.0.22621.2506

### Other software

OS Build Version: 10.0.22621.2506.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

Simplemente abrir el programa

### Expected result

Cargar widgets y lo que se supone debería estar en panel debido a que siempre me sale igual

### Actual result

No importa cuánto lo deje, ya lo vinculé a un repositorio de Github y en la ventana de panel se queda con la rueda de carga permanentemente sin mostrar avance

### Included System Information

Physical Memory: 15.34GB (5.98GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment]
Bing Translate: 
Panel loading

Steps to reproduce the bug
Simply open the program

Expected result
Loading widgets and what's supposed to be on dashboard because it always comes out the same

Actual result
No matter how long I leave it, I've already linked it to a Github repository and in the dashboard window it's left with the loading wheel permanently without showing progress

**Comment by krschau** [comment]
I believe this is caused by the problem fixed by #1712
