### ISSUE TITLE
Widgets getting moved/deleted automatically

### ISSUE THREAD

**Issue by iqnite** [microsoft/devhome#1850]
### Dev Home version

0.601.297.0

### Windows build number

10.0.22635.2700

### Other software

OS Build Version: 10.0.22635.2700.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

Add a core widget to the dashboard

### Expected result

The widget is placed where I drop it, and stays there forever

### Actual result

The widget is placed at a random position, and after some app updates it desappears

### Included System Information

Physical Memory: 13.83GB (3.64GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe

**Comment by iqnite** [comment]
[CoreWidgetProvider.zip](https://github.com/microsoft/devhome/files/13340940/CoreWidgetProvider.zip)

**Comment by iqnite** [comment]
GitHub widgets are not affected

**Comment by krschau** [comment]
@iqnite Thanks for the logs, they were very helpful! This might be a duplicate of #742. I can see you have MicrosoftWindows.Client.WebExperience version 423.30700.0.0 -- I would have thought the fix for this issue would be in that version, but it's possible it isn't. I'm going to do some investigating on my end about that. I have some work planned soon around #742, so I'm going to let the bot close this since I do think it's the same issue, but if I find anything out that indicates a different problem, I'll re-open.
