### ISSUE TITLE
Should we add PowerToys utilities to Dev Home?

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/devhome#1980]
### Provide a description of requested docs changes

We're looking into adding more features into Dev Home and we're considering adding a page for PowerToys to build in utilities. Dev Home is directly built into Windows and allows us to provide deep, feature-rich experiences for developers directly into the OS.

Our question is, do you want to see PowerToys in Dev Home? If so, which utilities would be most useful to you?

**Comment by Stanzilla** [comment]
How would that work? Adapting the features 1:1 or just linking to the PowerToys installer?

Imo the lines between what "Dev Home" means in my mind and "PowerToys" are very blurry. But I'm a dev. Not all PowerToys features are targeted at devs. If it was just me, Dev Home and PowerToys should merge. 

If you want the products stay separate, maybe move the features targeted at devs into Dev Home and remove them from PowerToys? But that would make people who only use PT unhappy because they have to install yet another thing and lose functionality if they don't act.

I would be interested to see what Telemetry you guys have on this, how many Dev Home users also have PowerToys installed and vice versa.

At the end, maybe Dev Home should stay a "hub" like it currently is and only display links to PowerToys, open the PT UI when it detects it is installed, offer to download when not?

**Comment by Stanzilla** [comment]
Would it make sense to turn all PowerTools into individual programs, like Dev Home extensions, that then register/install into Dev Home? With the PowerToys installer just installing all of them or giving you a choice? And then dev home handles management of options/updating via store etc?

**Comment by CanePlayz** [comment]
I'd generally love to see some of the PowerToys getting properly integrated into default Windows, either through Dev Home or otherwise.

**Comment by ttang4299** [comment]
PowerTools Awake alone provides so much utility. Like @CanePlayz  said, we would love to see this and other PowerTools integrated straight into Windows 11.

**Comment by ttang4299** [comment]
> What is the benefit to adding them in Dev home rather than getting them from their existing location?

@wolf99 There are 3rd party tools out there that work similar to PowerTools, but their obscurity does not lend them any credibility and they could become backdoors for malware.

Including PowerTools in Windows is great for anyone seeking the functions that PowerTools fulfills, without having to search elsewhere for untrustworthy 3rd party software because PowerTools has the backing of Microsoft. Including PowerTools will also increase visibility and awareness of the PowerTools themselves, as I was looking for a tool with functions like PowerTools Awake, but search engines could not lead me to PowerTools Awake itself. There are many more folks who could willingly get use out of the utility PowerTools provides.

**Comment by wolf99** [comment]
> Including PowerTools in Windows is great 

💯 Agreed, include them in *Windows*, that would be awesome... Not inside Dev home.

It's like putting regedit inside notepad. Both are useful things within Windows. Both are used by developers, power users, and others. Theoretically you could use them both as part of a single use case. But there's no benefit to putting one inside the other.

**Comment by ttang4299** [comment]
> 💯 Agreed, include them in _Windows_, that would be awesome... Not inside Dev home.

@wolf99 I'm all for their inclusion in Windows itself. I'm going to come clean and mention that I'm unfamiliar with Dev Home, as I'm not a developer myself. However, as a power user, these tools have broader appeal beyond devs, and I wanted to jump into the conversation here to advocate for their inclusion in Windows, given the developers here are listening.

**Comment by CanePlayz** [comment]
> > PowerTools Awake alone provides so much utility. Like @CanePlayz  said, we would love to see this and other PowerTools integrated straight into Windows 11.
> 
> Power Tools are good indeed, but what is the benefit to adding them in Dev home rather than getting them from their existing location?

Increase visibility and make them accessible to more people.

**Comment by ttang4299** [comment]
This entire time, I've been calling PowerToys "PowerTools"

I've edited my posts to correct the typo and apologize if you folks end up looking goofy in the quote replies.

**Comment by BenS13** [comment]
> ### Provide a description of requested docs changes
> We're looking into adding more features into Dev Home and we're considering adding a page for PowerToys to build in utilities. Dev Home is directly built into Windows and allows us to provide deep, feature-rich experiences for developers directly into the OS.
> 
> Our question is, do you want to see PowerToys in Dev Home? If so, which utilities would be most useful to you?

Or you should focus on finishing basic features first 🤯🤯🤯🤯🤯

**Comment by cinnamon-msft** [comment]
Thanks for all the feedback here, this has been super helpful :) I'm going to close this out and file a new issue for just adding a couple PowerToys to Dev Home and not the entire PowerToys experience.

Our goal is to bring in stable versions of specific PowerToys that make the most sense in Dev Home, i.e. Hosts File Editor, which was originally created with the intent to add to Dev Home when we built it for PowerToys
