### ISSUE TITLE
What is Dev Home and why does it exist?

### ISSUE THREAD

**Issue by tobico** [microsoft/devhome#2075]
Firstly I'd like to state that I'm highly appreciative of everything Microsoft is doing to improve the developer experience in Windows. That said, I'm very unclear about what Dev Home is, how it came to be installed on my computer, and why I might want to consider using it vs uninstalling it.

Having read the publicly posted documentation pages around it, all I can see is a grab bag of features without any clear indicator of how they're conceptually tied together, what the overall purpose of Dev Home as a tool is, and why I should consider using it over other tools with overlapping feature sets.

Generally it's intruiging to me that this project exists, however I think there's a lot of room for improvement around the communication surrounding the project, it's overall objectives and uses, and the situations under which it might be automatically installed on Windows.

**Comment by EmilAlipiev** [comment]
If i am not mistaken, when you install Win 11, there is a step where you select how you use this computer, if you select development purpose, it is auto installed. Uninstall not possible is bit of issue currently but i see there are some workaround suggested on google. Overall it is for newbies so far but as it is preview we hope that more should come.

**Comment by pawel38911** [comment]
Dev Home is bloatware. 

It exists mainly to further annoy Winows 11 users who thought they had liberated themselves from CandySaga only to discover DevHome on their computers one day to their horror.

Very few people understand what Dev Home could actually be used for (certainly not me). Dev Home is only good for giving Windows 11 users something to  release their rage that Microsoft still doesn't respect our opinion. Because it seems that we've already told Microsoft several times that we don't like bloatware, and that we prefer to decide for ourselves what applications we want to have on our computers.  Microsoft has made itself the administrator of our home computers, and took away a private user's authority to manage what he can and cannot do on his own private home computer.

**Comment by cinnamon-msft** [comment]
Dev Home is intended to be a centralized location for utilities and features that can help developers be successful on Windows. These features include helping you get set up quickly for development, helping you get into your development workflow seamlessly, as well as providing ways for you to monitor your projects. It also provides us with a platform to augment Windows in ways we couldn't before in order to add developer-centric features and settings. We're early in development but we're aiming to make this a feature-rich location in Windows just for devs.

**Comment by hitgub043** [comment]
> Dev Home is intended to be a centralized location for utilities and features that can help developers be successful on Windows. These features include helping you get set up quickly for development, helping you get into your development workflow seamlessly, as well as providing ways for you to monitor your projects. It also provides us with a platform to augment Windows in ways we couldn't before in order to add developer-centric features and settings. We're early in development but we're aiming to make this a feature-rich location in Windows just for devs.


If it's "just for devs", then why did you install it on my personal computer without permission? I'm not even a developer!
