### ISSUE TITLE
"Report a bug" list of installed extensions needs updating

### ISSUE THREAD

**Issue by krschau** [microsoft/devhome#2505]
### Dev Home version

0.12

### Steps to reproduce the bug

Go to Feedback, Report a bug, look at "Include installed Dev Home extensions and related packages".
Since Dev Home now has more than one extension included, it shows up more than once in the list.

### Expected result
One installation of Dev Home should only be listed once.

**Comment by Gobinath-B** [comment]
Here, There are two listed extensions are listed, 
```
Extensions: 
Microsoft.Windows.DevHome_0.1101.416.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.1200.442.0_x64__8wekyb3d8bbwe
```

So It is unnecessary to list the DevHome version in extension .
`
Microsoft.Windows.DevHome_0.1101.416.0_x64__8wekyb3d8bbwe`

Since we show the dev home version here,
![Screenshot (251)](https://github.com/microsoft/devhome/assets/81898167/f1192a6a-6308-4d58-8941-87b27dec2b20)

**Comment by Gobinath-B** [comment]
@krschau can i do this?

**Comment by krschau** [comment]
We're working on this. It requires a pretty fundamental change to how the extensions are defined.

**Comment by Gobinath-B** [comment]
Done

**Comment by krschau** [comment]
Depends on #2538
