### ISSUE TITLE
Environment progress bar could show progress.

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/devhome#2720]
### Other software

When Creating a VM, there are 3 steps:
1) download
2) unzip
3) compare hash

At least with the first one, you could show it grow to 100%. You know the size. Why not show progress?

### Steps to reproduce the bug

Create a hyperV VM from environments

### Expected result

steady progress bar showing percent complete

### Actual result

<img width="550" alt="image" src="https://github.com/microsoft/devhome/assets/2146880/c888bb5a-6ed4-4e23-8877-5da707fba6a4">

**Comment by shakersMSFT** [comment]
This is by design for consistency. Across the various environments we support, there is no guarantee that we will know for certain how long it will take or how close we are, which is why we have decided to do an indeterminate progress bar here. If the environment supports sharing the status, it will be shown in the card and updated as it continues.
