### ISSUE TITLE
Can't add domain users to Hyper-V Admin group

### ISSUE THREAD

**Issue by msft-mbrant** [microsoft/devhome#2995]
### Dev Home version

0.1401.505.0

### Windows build number

10.0.22631.3593

### Steps to reproduce the bug

Dev Home is asking me to add my user account to the Hyper-V admin groups on my domain joined machine. However, when looking at the group in Computer Management, I can only add local computer users to this local group.

Is the Hyper-V Admin Group membership really needed? I'm already Admin on my box and Hyper-V administration works just fine as an Admin.

### Expected result

Local admins should be able to use Dev Home Hyper-V functions without being a member of Hyper-V Admin group as non-local accounts can't join this group.

### Actual result

Dev Home refused to use Hyper-V because I'm not in the Hyper-V Admin Group on my machine, even though I have full control over Windows, hardware and Hyper-V

**Comment by bbonaby** [comment]
Hey @msft-mbrant , the reason why we prompt you to be added into the Hyper-V administrators group is because Dev Home does not run as admin. In order for the Hyper-V extension to use Hyper-V functionality like the Hyper-V powershell cmdlets (like the Hyper-V extension uses) or the Hyper-V WMI apis, the extensions process needs to be running with administrative privileges or the user needs to be in the Hyper-V Administrators group. (Then either reboot or log off/on again as the change won't take effect for the users logon session until the users security token is updated). That is why we prompt you to be added into the group and ask for you to reboot.


The Hyper-V Manager for example actually runs with elevated privileges: E.g if you change your UAC settings to the following:
![image](https://github.com/microsoft/devhome/assets/105318831/794d0c63-317e-43df-8d12-7cc0858935ea)

you'll see that the next time you launch the Hyper-V manager you'll be prompted with a UAC prompt even though you are an admin to your computer. Under the hood with normal UAC settings the Hyper-V manager is auto elevating and using a mechanism we can't use in Dev Home. I hope that answers your question.

When users are added to this group, they will be able to view and manage their VMs from Dev Home or any software that uses the Hyper-V apis outside of the Hyper-V manager without being in an elevated process.

**Comment by msft-mbrant** [comment]
I figured as much when I saw the function of the Hyper-V group. The "Add me" button however doesn't work in the DevHome (for me at least) and the Computer Management MMC GUI won't let me add non-local users. So we need to figure out a way we can get non-local users into that group but from a nice GUI. Ideally the button should work or perhaps a note "Run Dev Home as Admin to see Hyper-V Envs" but I guess that has security implications.

**Comment by huzaifa-d** [comment]
@msft-mbrant I haven't been able to repro this issue. Could you confirm if when you run Hyper-V Manager, you can create a VM and when you run DevHome it doesn't show that VM.

**Comment by msft-mbrant** [comment]
> @msft-mbrant I haven't been able to repro this issue. Could you confirm if when you run Hyper-V Manager, you can create a VM and when you run DevHome it doesn't show that VM.

Not sure what you mean. I've added my domain account to the local Hyper-V Admins group via the workaround and I can see the VMs created in Hyper-V Manager in my Dev Home Preview install.

![image](https://github.com/user-attachments/assets/c3403b08-dacb-4afd-8591-9bc3c017b755)

**Comment by huzaifa-d** [comment]
@msft-mbrant I mean that I have tested this scenario and it works as expected. We would need more info, but you have already used the workaround as you stated. You shouldn't have needed this because DevHome uses the same commands in the background. Do you have a repro?

P.S. - I have reached out to you on IM as well. We can continue the conversation there and update here when we have a resolution.

**Comment by huzaifa-d** [comment]
Discussed offline; this feature exists and works as expected.

**Comment by nasiralamreeki** [comment]
I’m able to reproduce this issue everytime I load the environments tab in dev home preview I get a notification prompting me to add my user to a hyper v user group and when I click the button to do that it doesn’t work and this notification nags me everytime I use dev home. This is not good user experience and should be addressed.
