### ISSUE TITLE
CPU utilization for system in PI does not match the utilization shown on the CPU widget on the DevHome dashboard

### ISSUE THREAD

**Issue by zadesai** [microsoft/devhome#3160]
### Steps to reproduce the bug

Launch DevHOme
Add CPU widget on the dashboard
From utilities page
Launch PI
The CPU utilization on top right in PI does not match the widget

### Expected result

The CPU utilization on top right in PI should match the widget

### Actual result

The CPU utilization on top right in PI does not match the widget

**Comment by dkbennett** [comment]
These won't match exactly, nor with task manager exactly due to different times they get the information, but they should all be very close. Task manager is very close to the CPU widget to the point where I'm confident it is getting the correct information, so I will add a fix for the PI counters to use the same methodology.
