### ISSUE TITLE
Sandbox icon is missing and thumbnail is the wrong size

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/devhome#3162]
### Steps to reproduce the bug

Have Windows Sandbox enabled
Navigate to environments page

### Expected result

The thumbnail image should be the same size as the others and there should be an icon to the left of "Windows Sandbox"

### Actual result

Looks like the thumbnail is at a different aspect ratio and there's no icon:
![image](https://github.com/microsoft/devhome/assets/48369326/d8a24058-3276-4c81-b68d-eaaafb79dd07)

**Comment by bbonaby** [comment]
@cinnamon-msft  Can you check if you have multiple versions of Dev Home installed like the Dev version and the Canary version? If so can you make sure the sandbox extension for the dev version is turned off. That might fix the icon missing issue. I do believe I've seen the icon showing up before.

About the thumbnail: @pehammer would either you or Christian be able to get us a new image for sandbox scaled appropriately just like we did for Hyper-V and Dev Box? Looks like we're using the light version of bloom here for sandbox

**Comment by cinnamon-msft** [comment]
I don't have a Dev version on this machine, just Preview and Canary, and Preview doesn't have Sandbox yet

**Comment by bbonaby** [comment]
Sounds, good thanks Kayla just wanted to make sure it wasn't one of those multiple dev home version issues.  Would you also be able to add the sandbox log file and the dev home log file to this issue as well when you can thanks!

**Comment by cinnamon-msft** [comment]
Here you go!
[devhome20240606.zip](https://github.com/user-attachments/files/15685505/devhome20240606.zip)

**Comment by bbonaby** [comment]
Thanks, looks like the issue is that the build constants are not present in the sandbox project e.g for Hyper-V:

we have [this line in the csproj file](https://github.com/microsoft/devhome/blob/9db92955056f1be932ee500c876b6f62ff626c3b/extensions/HyperVExtension/src/HyperVExtension/HyperVExtension.csproj#L107). It declares `STABLE_BUILD` and `CANARY_BUILD` as constants for the project. The Sandbox uses these same constants in this [file](https://github.com/microsoft/devhome/blob/9db92955056f1be932ee500c876b6f62ff626c3b/extensions/WindowsSandboxExtension/Constants.cs#L27) just like we do for HyperV [here](https://github.com/microsoft/devhome/blob/9db92955056f1be932ee500c876b6f62ff626c3b/extensions/HyperVExtension/src/HyperVExtension/Constants.cs#L18). However since those constants aren't declared in the sandbox csproj file, the ifdef's go into the else case, where it looks for this file:

`ms-resource://microsoft.windows.devhome.dev/Files/Assets/windows-sandbox-icon.png`

and you'll notice that the package its using is microsoft.windows.devhome.**dev** , which like you said above doesn't exist on your machine. So therefore an image isn't found.

This should be a simple fix though, we just need to declare those constants in the sandbox csproj file in here somewhere: https://github.com/microsoft/devhome/blob/9db92955056f1be932ee500c876b6f62ff626c3b/extensions/WindowsSandboxExtension/WindowsSandboxExtension.csproj

**Comment by krschau** [comment]
Sandbox extension has been removed, so this issue is no longer applicable.
