### ISSUE TITLE
Two dev box options appearing in create environment UI

### ISSUE THREAD

**Issue by acangialosi** [microsoft/devhome#3349]
### Dev Home version

0.1401.500.0

### Windows build number

10.0.22635.3858

### Other software

OS Build Version: 10.0.22635.3858.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.4

### Steps to reproduce the bug

Click "Create Environment" button

### Expected result

One option appears to create Dev Boxes

### Actual result

Two options appear instead.
![image](https://github.com/microsoft/devhome/assets/5457010/4cc9daa3-1420-4b98-a31b-c07d953b319f)
![Uploading image.png…]()

### Included System Information

CPU: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Physical Memory: 31.6GB (18.23GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeAzureExtension.Canary_0.900.500.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))
Microsoft.Windows.DevHomeAzureExtension_0.1000.533.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Hyper-V Extension)

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.16300.0.0_x64__cw5n1h2txyewy

**Comment by bbonaby** [comment]
looks like the issue here is that you have two versions of the Azure extension installed on your machine:

Microsoft.Windows.DevHomeAzureExtension.Canary_0.900.500.0_x64__8wekyb3d8bbwe **(Dev Home Azure Extension (Canary))**
Microsoft.Windows.DevHomeAzureExtension_0.1000.533.0_x64__8wekyb3d8bbwe **(Dev Home Azure Extension (Preview))**

I believe if you uninstall one or disable one through Dev Home's extensions page you should then only see one.

**Comment by huzaifa-d** [comment]
Like Brandon mentioned, this is due to having two version of the extension installed. Closing out the bug.
