### ISSUE TITLE
Dev Home itself should not shown in the extension list

### ISSUE THREAD

**Issue by jiayac** [microsoft/devhome#3382]
### Steps to reproduce the bug

Go to extension page.
![image](https://github.com/microsoft/devhome/assets/65691598/213504dd-0297-4794-900a-02346b5dc727)

### Expected result

It should only show extensions

### Actual result

It shows not only extensions but also Dev Home App itself.

**Comment by krschau** [comment]
Hi @jiayac -- this is actually the expected behavior. It might not be super clear at first, but the list in your screenshot is actually the list of extension *providers*. If you expand the item, you can see all the extensions that provider contains. You'll see that for Dev Home, you can actually choose to disable the "Hyper-V Extension" underneath it. That's why "Dev Home" is in the list.
