### ISSUE TITLE
[Environments reliability] Dev Box operations: Page doesn't show the correct status of a long running operation

### ISSUE THREAD

**Issue by huzaifa-d** [microsoft/devhome#3448]
### Steps to reproduce the bug

1. Go to Environments and let the Dev Boxes load.
2. Stop one of them and wait.

### Expected result

The status should change to stopped in some time.

### Actual result

The status either takes too long or needs to be sync'd to get the right status.

**Comment by bbonaby** [comment]
2 things for this one: Once an operation starts, we poll the operation in the Dev Center once per minute until its completed. We could decrease this by decreasing the time here: https://github.com/microsoft/DevHomeAzureExtension/blob/5032d6fa2989de27508971e55553f8fff9314672/src/AzureExtension/Services/DevBox/TimeSpanService.cs#L34. For creation we poll every 3 minutes since that takes a longer time (could be over an hour for some orgs).

The other thing of note, is I believe if an operation (other than creation) is started outside of Dev Home. We show the progress bar in Dev Home, but we don't poll anything so to the user it looks like something is happening but its actually not. Which is probably why it looks like it only completes after pressing the sync button. In this case we can either starting polling for changes to the state of the Dev Box if we see its state is starting/stopping/deleting etc and there were no operations initiated by us. Or see if there is a way to retrieve the state of the current operation in the Dev Center and poll the operation until its completed (also assuming it wasn't initiated by us).

**Comment by huzaifa-d** [comment]
Reached out to the Dev Box team for more clarity. The long operations taking 10+ minutes is expected. And the code correctly polls for updates; tested over multiple days/dev boxes/dev centers.
