### ISSUE TITLE
[Environments reliability] Dev Box Creation Error: A virtual machine with this name already exists 

### ISSUE THREAD

**Issue by bbonaby** [microsoft/devhome#3661]
### Steps to reproduce the bug

Attempt to create a Dev Box with the same name as an existing one in a project

This accounts for 20% of all Dev Box creation failures that we see in Dev Home once the Dev Box provider submits the request to the Dev Center.

### Expected result

We should prevent the user from being able to attempt to create one with the same name, and an error should be shown beforehand.

### Actual result

The user is able to attempt to create a Dev Box with the same name, and so the Dev Box creation fails.

**Comment by hamza-usmani** [comment]
I would argue this is a P1, considering it accounts for failures and is breaking our current experience

**Comment by huzaifa-d** [comment]
I have examined the dev change that would be needed for this, and this adds an additional REST API call. The performance penalty for which is +30% for a page that is already flagged for being slow (https://github.com/microsoft/devhome/issues/3637). Additionally, looking at the errors from the past two months as of this comment, there are no occurrences. As such I don't think a fix is worthwhile performance wise, especially since we show an error immediately following the operation already. 
Please reopen if needed.
