### ISSUE TITLE
Launching environments, sometimes it says I need to log on in the settings pane to see devbox

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/devhome#3854]
### Steps to reproduce the bug

Sometimes when I go to the environments page, i get an error about needed to log on to devbox in the settings pane. Why? AFAIK i have not changed anything.
If I close DevHome run DevBox portal from the web, then run DevHome the error persists.

As far as I could tell, the error only went away when I navigated to settings and observed that Azure was already signed in.
Of note, there were 2 azure accounts.
![image](https://github.com/user-attachments/assets/37e188e7-9c28-4a4c-8c1a-84626d48e8c2)

### Expected result

DevBox just connects and works like the other environments.

### Actual result

See steps

**Comment by huzaifa-d** [comment]
> Sometimes when I go to the environments page, i get an error about needed to log on to devbox in the settings pane. Why? AFAIK i have not changed anything.

This is because there needs to be an account for which Dev Home will show the Dev Boxes. I have pushed a PR with a better user message in the meantime.

> If I close DevHome run DevBox portal from the web, then run DevHome the error persists.

The two, Dev Home and Dev Box web portal, are mutually exclusive.

> As far as I could tell, the error only went away when I navigated to settings and observed that Azure was already signed in.

Starting Dev Home again sets the currently logged in user as the default account. This is probably what happened. This can be replicated if you log off from Dev Home, restart Dev Home and go to the Environments page.

> Of note, there were 2 azure accounts.

This is because you have two Azure extensions enabled - Preview and Canary.
Please make sure you have only one of these installed/enabled.
