### ISSUE TITLE
Environments: Error should help me solve action

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/devhome#3855]
### Steps to reproduce the bug

First: it would be ideal for errors not to occur.
Second: can we fix them automatically?
Third: Let's give the user an quick fix instead of just text.

In this case the error that I get from our UI is that devbox needs me to log in. Why not add functionality to "Click this message to login, or click this message to go to the settings pane"

### Expected result

Click here to fix.

### Actual result

<img width="269" alt="image" src="https://github.com/user-attachments/assets/97fa124b-e5cb-421e-a20f-e6a4251596c0">

**Comment by huzaifa-d** [comment]
1. We can't really prevent this error.
2. We can't fix this error automatically, but we can try to get the logged in user account and set it to default.
3. The error is actually shown from the Azure extension. And an action, if any, will have to come from the Azure extension. Navigation to the Settings page won't be possible since the extension doesn't have that kind of control over the host, Dev Home. But we can pursue the idea presented above. 

And I think that this should be a feature request, instead of a bug.
