### ISSUE TITLE
[Feedback] Feedback page should be a line item in the Settings tab

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhome#539]
### Steps to reproduce the bug

Description
Feedback currently has it's own entry point in the left nav. It should be grouped in under the settings entry point, as a line item in settings.

**Comment by jaypey** [comment]
May I take this one? I would like to start contributing and familiarizing myself with the codebase.

**Comment by EricJohnson327** [comment]
Hey @jaypey, thank you for the interest in contributing!  It's all yours!  Please feel free to reach out with any questions.

**Comment by cinnamon-msft** [comment]
Hey @jaypey! Checking in on this, we're planning a release soon - would you still like to do this feature or shall we reassign? Thanks!

**Comment by jaypey** [comment]
Hey @cinnamon-msft , unfortunately I've had problems building the project last week due to nuget packages that seemed locked behind an auth. I found #734 which seems related to my problem, but I haven't been able to resolve it yet.

I see that the milestone is due for June 16, could I get this week to work on it and update you then?
