### ISSUE TITLE
Dev Home does not detect my IDEA effectively

### ISSUE THREAD

**Issue by Melendez1209** [microsoft/devhome#788]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Dev Home does not detect my IDEA effectively, Pycharm (EAP) is installed via Jetbrains Toolbox, and Android Studio is a preview version.

### Expected result

Dev Home will be able to detect the IDEAs I mentioned effectively and open them properly

### Actual result

Dev Home does not detect my IDEA effectively, Pycharm (EAP) is installed via Jetbrains Toolbox, and Android Studio is a preview version.
![image](https://github.com/microsoft/devhome/assets/92637479/e908da70-7e70-4915-832d-a273a50f690f)
![image](https://github.com/microsoft/devhome/assets/92637479/c28d123d-0918-46d6-90f4-a3ebcaf533b9)

### Included System Information

CPU: 12th Gen Intel(R) Core(TM) i7-12700H
Physical Memory: 15.71GB (9.43GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by localden** [comment]
Related to #717

**Comment by florelis** [comment]
DevHome uses winget to detect installed apps, and winget currently doesn't do great matching packages that can have multiple installs side by side (like Preview/Stable version), or that have different editions (like Community/Enterprise) since those have different product codes in the registry.

Probably worth it to open an issue on the winget-cli repo, or add a 👍 to some of the existing issues, as the number of reactions is something used there to prioritize.
See:
microsoft/winget-cli#2803
microsoft/winget-cli#2129
microsoft/winget-cli#147

**Comment by Melendez1209** [comment]
OK, fine. It's not exactly what I expected. The appropriate translation is already at the top. I'm also working on a Winui app recently. As an individual developer, I don't think this approach of requiring a translation team works for me. Do you have any other suggestions?[The project](https://github.com/Melendez1209/Known)

**Comment by Melendez1209** [comment]
Ok, I see.
