### ISSUE TITLE
Add a option to search or add IDE/Tools already installed 

### ISSUE THREAD

**Issue by robsoneisinger** [microsoft/devhome#801]
### Suggested new feature or improvement

I loved the Dev Home proposal, however, I have already installed a few tools and IDEs. So, you should improve Dev Home adding the option to search for already installed tools/ide and add it to DEV Home, or import the configuration, install it inside Dev home and remove the old version (if not integrated). 

### Scenario

Tool/IDE already installed.

**Comment by florelis** [comment]
I'd like to understand the scenario a bit more. What would you like to do from Dev Home with the installed app?
Installing from Dev Home is the same as manually downloading the installer and running it, so there's no difference whether you install it from Dev Home or not.

**Comment by denelon** [comment]
Do you see this as it relates to:
* #1067 

Or is this a different ask?

**Comment by robsoneisinger** [comment]
> I'd like to understand the scenario a bit more. What would you like to do from Dev Home with the installed app? Installing from Dev Home is the same as manually downloading the installer and running it, so there's no difference whether you install it from Dev Home or not.

When you search for PyCharm, the interface lists 4 results, none of them installed. However, I do have a version installed on my computer (PyCharm Professional). 

![image](https://github.com/microsoft/devhome/assets/89414538/a5126b9f-1f41-4e9b-bbad-a355e2e848d2)

However, when searching for VS Code, the interface do recognize that I have it installed (I did it using Dev Home):

![image](https://github.com/microsoft/devhome/assets/89414538/c84ec57e-0eb9-4a7a-ad85-dd41063a1a9b)

So, I'm asking for a option to scan for already installed IDE's to list and search it using Dev Home. No just that, you can also add a widget to open your IDE direclty from Dev Home, the same way you can open a ssh session direclty from there.

**Comment by robsoneisinger** [comment]
Also, instead of listing options, maybe offer to open it if already installed. This would make Dev home a Hub to easily access all dev tools I have. Ok that I would prefer to directly open a project from said IDEs instead of open the IDE (you can do it using a shortcut or from the taskbar). 

So, when I said "add" it to Dev Home, consider it as scan/add it to the interface so I can do more stuff direct from Dev Home.

**Comment by florelis** [comment]
Re: PyCharm not marked as installed:

It's weird that it doesn't detect that PyCharm is already installed. It should show that. We're using winget for handling apps and it does look for installed apps, though sometimes it has trouble matching an installed app to one of the apps in the catalog.

Could you try doing `winget list PyCharm` from the terminal and checking the result? It should output a table like this one:
```
Name             Id                             Version  Source
----------------------------------------------------------------
PyCharm 2022.3.2 JetBrains.PyCharm.Professional 2022.3.2 winget
```

If it has a Source, then winget is able to match it with one of the packages in its catalog and the issue would be on Dev Home for not retrieving that information right to mark it as installed.

Otherwise, it may be a winget matching issue (i.e., not Dev Home). If you don't see the source from that command, a good first thing to check would be the winget version with `winget --version` or `winget --info`; it may be that you have an older version of it as we have been improving the matching there. If that's not it, we'd have to look at it from the winget side.

---

Re: Opening IDEs from this page:

If you want to open an empty IDE, this would probably have to be through winget too. It currently does not have an option to launch an installed package, you can open an issue over at [winget-cli](https://github.com/microsoft/winget-cli) or give a thumbs-up 👍 to one of the existing issues to help us prioritize it, like microsoft/winget-cli#2280

If you want to open a specific project on the IDE you use for it, I think that would be a new feature related to knowing what repos you have and what you need to open. I'm sure there's several issues about that and it would be good to have all these requests pointed to a single one so it's easier to prioritize, but I'm not sure which issue is being used for that.

**Comment by robsoneisinger** [comment]
The winget had returned nothing, but now I understand the issue: I installed PyCharm using JetBrains ToolBox. *facepalm

I'm closing this issue, I guess that not something that winget can handle. And I will search for other issues related to using Dev Home as a shortcut to open my installed IDEs or projects.

Thank you so much.

> Re: PyCharm not marked as installed:
> 
> It's weird that it doesn't detect that PyCharm is already installed. It should show that. We're using winget for handling apps and it does look for installed apps, though sometimes it has trouble matching an installed app to one of the apps in the catalog.
> 
> Could you try doing `winget list PyCharm` from the terminal and checking the result? It should output a table like this one:
> 
> ```
> Name             Id                             Version  Source
> ----------------------------------------------------------------
> PyCharm 2022.3.2 JetBrains.PyCharm.Professional 2022.3.2 winget
> ```
> 
> If it has a Source, then winget is able to match it with one of the packages in its catalog and the issue would be on Dev Home for not retrieving that information right to mark it as installed.
> 
> Otherwise, it may be a winget matching issue (i.e., not Dev Home). If you don't see the source from that command, a good first thing to check would be the winget version with `winget --version` or `winget --info`; it may be that you have an older version of it as we have been improving the matching there. If that's not it, we'd have to look at it from the winget side.
> 
> Re: Opening IDEs from this page:
> 
> If you want to open an empty IDE, this would probably have to be through winget too. It currently does not have an option to launch an installed package, you can open an issue over at [winget-cli](https://github.com/microsoft/winget-cli) or give a thumbs-up 👍 to one of the existing issues to help us prioritize it, like [microsoft/winget-cli#2280](https://github.com/microsoft/winget-cli/issues/2280)
> 
> If you want to open a specific project on the IDE you use for it, I think that would be a new feature related to knowing what repos you have and what you need to open. I'm sure there's several issues about that and it would be good to have all these requests pointed to a single one so it's easier to prioritize, but I'm not sure which issue is being used for that.

**Comment by denelon** [comment]
No worries. I've seen some similar fun with using NPM to install Node.js.
