### ISSUE TITLE
Ensure dialog "exit" buttons are consistently styled

### ISSUE THREAD

**Issue by slymanoworld** [microsoft/devhome#916]
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1778

### Other software

OS Build Version: 10.0.22621.1778.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Nella dashboard, cliccando il tasto di aggiunta del widget

### Expected result

Ha fatto il suo lavoro, tuttavia sto segnalando qualche inconsistenza estetica.

### Actual result

La linea active che indica la sezione attuale non è al bordo della sezione selezionata, è all'interno. Inoltre, il bottone di uscita della 'modal' per l'aggiunta dei widget dovrebbe avere più margin rispetto alla topbar.

**Comment by krschau** [comment]
Bing translate:

Inconsistencies in the 'modal' that appears for adding widgets

Steps to reproduce the bug
In the dashboard, click the add widget button

Expected result
It has done its job, however I am pointing out some aesthetic inconsistencies.

Actual result
The active line indicating the current section is not at the edge of the selected section, it is inside. In addition, the exit button of the 'modal' for adding widgets should have more margin than the topbar.

**Comment by krschau** [comment]
@slymanoworld For the line indicating the current selection, that's the default behavior of the XAML NavigationView control, and is by design. (Circled in red here, just to make sure we're talking about the same thing.)
![image](https://github.com/microsoft/devhome/assets/47155823/5feb5208-6d0d-45e4-bc6b-5f3689a5ba30)

I do think we need to do a pass on all the exit buttons in the app, and make sure their size/margins/padding are consistent.
